WIP: Implement communication task
fmfi-svt-deadlock/reader-sw pull request #4
Opened 2018-04-18 13:37 UTC by adam-dej

This PR implements the communication task.

Things left to do:

  - [ ] Get DCRCP and DCL2 PRs merged and update libdeadcom submodule accordingly (https://github.com/fmfi-svt-deadlock/libdeadcom/pull/1 and https://github.com/fmfi-svt-deadlock/libdeadcom/pull/2)
  - [ ] Fix transmit function returning as soon as bytes are copied to the output buffer, as opposed to transmitted
  - [ ] Fix hardcoded length constants

2018-05-02 14:20 UTC, adam-dej commented
This PR is no longer WIP, @lubo please take a look

2018-05-02 14:49 UTC, lubo requested changes

2018-05-02 14:49 UTC, lubo commented on src/tasks/comm-task/comm-task.c
> +        chSysHalt("null from inifinitely waiting guarded pool");
\* infinitely

2018-05-02 14:49 UTC, lubo commented on src/tasks/comm-task/comm-task.c
> +        chSysHalt("null from inifinitely waiting guarded pool");
\* infinitely

2018-05-02 14:49 UTC, lubo commented on src/tasks/comm-task/comm-task.c
> +        chSysHalt("null from inifinitely waiting guarded pool");
\* infinitely

2018-05-02 14:49 UTC, lubo commented on src/tasks/comm-task/comm-task.c
> +    for (i = 0; i < uids_len; i++) {
Can't you move definition of `i` into scope of this for?

2018-05-02 14:49 UTC, lubo commented on src/tasks/comm-task/comm-task.c
> +        //TODO generate heartbeat
Is this TODO harmless?

2018-05-02 14:49 UTC, lubo commented on src/tasks/comm-task/comm-task.c
> +        // TODO generate heartbeat
Is this TODO harmless?

2018-05-03 08:11 UTC, adam-dej commented on src/tasks/comm-task/comm-task.c
> +        //TODO generate heartbeat
Yes, heartbeats will be implemented in Master Task, which will be in a different PR

2018-05-03 08:11 UTC, adam-dej commented on src/tasks/comm-task/comm-task.c
> +        // TODO generate heartbeat
Yes, heartbeats will be implemented in Master Task, which will be in a different PR

2018-05-03 08:11 UTC, adam-dej commented on src/tasks/comm-task/comm-task.c
> +        chSysHalt("null from inifinitely waiting guarded pool");
fixed

2018-05-03 08:11 UTC, adam-dej commented on src/tasks/comm-task/comm-task.c
> +        chSysHalt("null from inifinitely waiting guarded pool");
fixed

2018-05-03 08:11 UTC, adam-dej commented on src/tasks/comm-task/comm-task.c
> +        chSysHalt("null from inifinitely waiting guarded pool");
fixed

2018-05-03 08:11 UTC, adam-dej commented on src/tasks/comm-task/comm-task.c
> +    for (i = 0; i < uids_len; i++) {
moved

2018-05-03 13:00 UTC, lubo approved these changes

2018-05-03 13:01 UTC, merged